version: 2

jobs:

  docs-build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v9-cargo-cache-docs-{{ arch }}-{{ .Branch }}-
            - v9-cargo-cache-docs-{{ arch }}-

      # Install nightly
      - run:
          name: Install Rust nightly
          command: rustup update nightly && rustup default nightly

      # Show versions
      - run:
          name: Show versions
          command: rustc --version && cargo --version

      # Install mdbook
      - run:
          name: Install mdbook
          command: >
            (test -x $CARGO_HOME/bin/cargo-install-update || cargo install cargo-update)
            && (test -x $CARGO_HOME/bin/mdbook || cargo install --vers "^0.2" mdbook)
            && (test -x $CARGO_HOME/bin/mdbook-linkcheck || cargo install --vers "^0.2" mdbook-linkcheck)
            && (test -x $CARGO_HOME/bin/mdbook-bookimport || cargo install --vers "^0.1" mdbook-bookimport)
            && mv ~/.gitconfig ~/.gitconfig.disabled  # Workaround for https://github.com/nabijaczleweli/cargo-update/issues/100
            && cargo install-update -a
            && mv ~/.gitconfig.disabled ~/.gitconfig

      # Print versions in case we need to debug a failed job
      - run:
          name: Print Versions
          command: >
            mdbook -V
            && mdbook-linkcheck -V
            && mdbook-bookimport -V

      # Build docs
      - run:
          name: Build docs
          command: >
            (cd book && RUST_LOG=debug mdbook build)
            && cargo doc --no-deps -p virtual-dom-rs -p css-rs-macro -p html-macro -p router-rs
            && cp -R target/doc book/book/api

      - persist_to_workspace:
          root: book
          paths: book

      # Save cache
      - save_cache:
          key: v9-cargo-cache-docs-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v9-cargo-cache-docs-{{ arch }}-
          paths:
            - target
            - /usr/local/cargo

  docs-deploy:
    docker:
      - image: node:10
    steps:
      - checkout
      - attach_workspace:
          at: book
      - run:
          name: Disable jekyll builds
          command: touch book/book/.nojekyll
      - run:
          name: Install and configure dependencies
          command: >
            npm install -g gh-pages@2
            && git config user.email "ci-build@circleci"
            && git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "71:95:d0:f5:0d:f6:fe:2a:9d:62:d7:4e:9a:6f:8e:8d"

      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist book/book

workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
